controller_list:
  - name: fake_iiwa_manipulator_controller
    joints:
      - iiwa_1_joint_1
      - iiwa_1_joint_2
      - iiwa_1_joint_3
      - iiwa_1_joint_4
      - iiwa_1_joint_5
      - iiwa_1_joint_6
      - iiwa_1_joint_7
      - iiwa_2_joint_1
      - iiwa_2_joint_2
      - iiwa_2_joint_3
      - iiwa_2_joint_4
      - iiwa_2_joint_5
      - iiwa_2_joint_6
      - iiwa_2_joint_7

initial:  # Define initial robot poses.
  - group: iiwa_1
    pose: iiwa_1_up
  - group: iiwa_2
    pose: iiwa_2_up